//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BT3_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        BT3_Client.ServiceReference1.HelloWorldResponse HelloWorld(BT3_Client.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<BT3_Client.ServiceReference1.HelloWorldResponse> HelloWorldAsync(BT3_Client.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCalculator", ReplyAction="*")]
        int AddCalculator(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCalculator", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddCalculatorAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractCalculator", ReplyAction="*")]
        int SubtractCalculator(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractCalculator", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubtractCalculatorAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplyCalculator", ReplyAction="*")]
        int MultiplyCalculator(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiplyCalculator", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplyCalculatorAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DivideCalculator", ReplyAction="*")]
        double DivideCalculator(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DivideCalculator", ReplyAction="*")]
        System.Threading.Tasks.Task<double> DivideCalculatorAsync(int a, int b);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BT3_Client.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BT3_Client.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public HelloWorldRequestBody() {
        }
        
        public HelloWorldRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BT3_Client.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BT3_Client.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : BT3_Client.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<BT3_Client.ServiceReference1.WebService1Soap>, BT3_Client.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BT3_Client.ServiceReference1.HelloWorldResponse BT3_Client.ServiceReference1.WebService1Soap.HelloWorld(BT3_Client.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string name) {
            BT3_Client.ServiceReference1.HelloWorldRequest inValue = new BT3_Client.ServiceReference1.HelloWorldRequest();
            inValue.Body = new BT3_Client.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.name = name;
            BT3_Client.ServiceReference1.HelloWorldResponse retVal = ((BT3_Client.ServiceReference1.WebService1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BT3_Client.ServiceReference1.HelloWorldResponse> BT3_Client.ServiceReference1.WebService1Soap.HelloWorldAsync(BT3_Client.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<BT3_Client.ServiceReference1.HelloWorldResponse> HelloWorldAsync(string name) {
            BT3_Client.ServiceReference1.HelloWorldRequest inValue = new BT3_Client.ServiceReference1.HelloWorldRequest();
            inValue.Body = new BT3_Client.ServiceReference1.HelloWorldRequestBody();
            inValue.Body.name = name;
            return ((BT3_Client.ServiceReference1.WebService1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        public int AddCalculator(int a, int b) {
            return base.Channel.AddCalculator(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddCalculatorAsync(int a, int b) {
            return base.Channel.AddCalculatorAsync(a, b);
        }
        
        public int SubtractCalculator(int a, int b) {
            return base.Channel.SubtractCalculator(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SubtractCalculatorAsync(int a, int b) {
            return base.Channel.SubtractCalculatorAsync(a, b);
        }
        
        public int MultiplyCalculator(int a, int b) {
            return base.Channel.MultiplyCalculator(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyCalculatorAsync(int a, int b) {
            return base.Channel.MultiplyCalculatorAsync(a, b);
        }
        
        public double DivideCalculator(int a, int b) {
            return base.Channel.DivideCalculator(a, b);
        }
        
        public System.Threading.Tasks.Task<double> DivideCalculatorAsync(int a, int b) {
            return base.Channel.DivideCalculatorAsync(a, b);
        }
    }
}
